// Shared prescriptions seed data for pharmacy views
export const prescriptionsData = [
  {
    id: 'RX001',
    patientName: 'Siam Ahmed',
    patientId: 'P001',
    age: '21',
    gender: 'Male',
    bloodType: 'A+',
    prescriptionsCount: '5',
    allergies: 'Penicillin, Sulfa drugs',
    conditions: 'Hypertension, Type 2 Diabetes',
    diagnosis: 'Fever\nMalaria\nDengue',
    medications: 'dasf\nQuantity: fdsfsd | Frequency: asdfsad | Duration: asdf\nNapa\nQuantity: 90 | Frequency: 1-0-1 | Duration: 1 month(s)',
    doctor: 'Dr. Alfred',
    status: 'Processed',
  },
  {
    id: 'RX002',
    patientName: 'Patient Y',
    patientId: 'P002',
    age: '34',
    gender: 'Female',
    bloodType: 'B+',
    prescriptionsCount: '3',
    allergies: 'None reported',
    conditions: 'Hypertension',
    diagnosis: 'Migraine',
    medications: 'Ibuprofen 400mg - 20 tablets',
    doctor: 'Dr. Alfred',
    status: 'Processed',
  },
  {
    id: 'RX003',
    patientName: 'Patient N',
    patientId: 'P003',
    age: '45',
    gender: 'Male',
    bloodType: 'O+',
    prescriptionsCount: '4',
    allergies: 'Aspirin',
    conditions: 'Hyperlipidemia',
    diagnosis: 'Hypertension',
    medications: 'Lisinopril 10mg - 60 tablets',
    doctor: 'Dr. Alfred',
    status: 'Processed',
  },
  {
    id: 'RX004',
    patientName: 'Patient M',
    patientId: 'P004',
    age: '52',
    gender: 'Female',
    bloodType: 'AB+',
    prescriptionsCount: '6',
    allergies: 'None',
    conditions: 'Prediabetes',
    diagnosis: 'Type 2 Diabetes',
    medications: 'Metformin 500mg - 90 tablets',
    doctor: 'Dr. Smith',
    status: 'Pending',
  },
  {
    id: 'RX005',
    patientName: 'Patient Z',
    patientId: 'P005',
    age: '38',
    gender: 'Male',
    bloodType: 'A+',
    prescriptionsCount: '2',
    allergies: 'None',
    conditions: 'Hyperlipidemia',
    diagnosis: 'Cholesterol management',
    medications: 'Atorvastatin 20mg - 30 tablets',
    doctor: 'Dr. Jones',
    status: 'Processed',
  },
];
